### ISSUE TITLE
Permettre de relancer un diagnostic existant

### ISSUE THREAD

**Issue by pabois** [noesya/coop.noesya.diagnostic#1]
Il faut pouvoir relancer un diagnostic sur une URL déjà testée.

Cela doit créer un historique sur la page de résultat, avec un tableau dans un premier temps si nécessaire, puis dans l'absolu une timeline un peu jolie

**Comment by SebouChu** [comment]
- [ ] La recherche d'une URL doit amener sur le dernier diagnostic en date de cette URL
- [ ] Avoir un bouton pour recréer un diagnostic pour cette URL
- [ ] Lister sur la page de résultats tous les diagnostics pour la même URL

**Comment by arnaudlevy** [comment]
Manque le graph, mais c'est ok
