### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by alexisben** [noesya/coop.noesya.diagnostic#2]
- [x] "votre site est certainement au-dessus" --> pas vérifiable du tout comme info
![image](https://user-images.githubusercontent.com/4630530/142925444-09a16a75-856b-42a7-830a-a42b7159ce47.png)

- [x] Pas de "s" et peut-être "gramme de CO2 généré à chaque visite de la page". Ne serait-ce pas plus juste de parler d'équivalent CO2 ?
![image](https://user-images.githubusercontent.com/4630530/142925811-0fe2128b-a20a-43ff-b04c-b7b7695c63df.png)

- [x] "La situation est assez grave, la page est trop grosse", "En dessous de 90%, ce n'est pas bon." --> mitigé sur le ton, ça fait un peu moralisateur / donneur de leçon : est-ce qu'on peut pas rester factuel et mettre des comparaisons pour que l'utilisateur se rende mieux compte ? La partie "Pourquoi agir ?" fonctionne très bien.

- [ ] Mettre des ancres sur les grosses statistiques pour scroller sur les parties concernées plus bas ?

**Comment by arnaudlevy** [comment]
c'est du CO2 sur websitecarbon, pas de l'équivalent CO2

**Comment by arnaudlevy** [comment]
pour les ancres, bof, les 3 premiers sont le premier paragraphe, le 4e est plié

**Comment by arnaudlevy** [comment]
j'ai remplacé grave par problématique
